name = "sanmemory"
main = "worker.js"
compatibility_date = "2025-01-01"

# Servir est√°ticos (HTML/CSS/JS) a partir de ./public
assets = { directory = "./public", binding = "ASSETS" }

[durable_objects]
bindings = [
  { name = "ROOM", class_name = "Room" }
]

[[migrations]]
tag = "v1"
new_classes = ["Room"]
