name = "sanmemory"
main = "worker.js"
compatibility_date = "2024-11-01"

[site]
bucket = "./public"

[durable_objects]
bindings = [
  { name = "ROOM", class_name = "Room" }
]

[[migrations]]
tag = "v1"
new_classes = ["Room"]
